### ISSUE TITLE
YouTube Music Brand Account Support

### ISSUE THREAD

**Issue by anispwyn** [FoxxMD/multi-scrobbler#106]
is description even needed? uhm

so basically
brand token and an actual account token are the same token as you can see below
![image](https://github.com/FoxxMD/multi-scrobbler/assets/36318840/abfe63cc-9bf0-40be-9264-c3376200b194) (there is some different after some part, i dont know if its possible to use that to check if its a brand account or not)

and the services just use the actual account (not brand accounts) for scrobbling
so i would like to see this get implemented some days

**Comment by FoxxMD** [comment]
The image you posted does not show the [`Cookie` header](https://foxxmd.github.io/multi-scrobbler/docs/configuration#youtube-music), specified in the docs, which is what is used to identify the account. 

You should try logging in as the personal account, or switch to it, and checking if the `Cookie`and `X-Goog-AuthUser` headers found there is the same as when you are using the brand account. If they are different you can probably use the normal account cookie to monitor just plays from that account.

If they are not different I'm sure its possible to differentiate which account is used because the youtube music library, [`youtube-music-ts-api`](https://github.com/nickp10/youtube-music-ts-api), MS uses is basically just scraping the rendered web page for text and account name should be shown on the webpage (upper right corner when logged in, I think). Implementing that functionality is out of scope for MS, though. You could open a PR on `youtube-music-ts-api` and implement the functionality yourself. I'd be happy to bump the library version so support that.
