### ISSUE TITLE
Restart an Idle Client

### ISSUE THREAD

**Issue by Cwavs** [FoxxMD/multi-scrobbler#114]
This isn't strictly a bug or a feature request.

**Describe the bug**

**To Reproduce**
1. Client has some sort of failure (e.g downtime)
2. Mutli-scrobbler tries to scrobble to it but fails 5 times
3. Client becomes idle
4. Client doesn't seem to resume activity, and scrobbles continue to queue up

**Expected behavior**
User is presented with a way to re-activate the client and clear the queued scrobbles, or it automatically re-attempts on a new scrobble.

**Logs**
If possible reproduce the issue with [debug logging ON](https://github.com/FoxxMD/multi-scrobbler/blob/master/docsite/docs/FAQ.md#turn-on-debug-logging)

https://privatebin.net/?4a953a85837cbc1f#6vM9m5eYJ6J8YYSzapVqhu93L8a4ydwTpfxzx666q6SS

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: 0.6.2 on podman
- jellyfin: 10.8.13

**Additional context**
I've seen this happen a few times recently. When [ListenBrainz went down due to a testing mishap](https://blog.metabrainz.org/2023/11/04/listenbrainz-service-incident/), this seems to have caused a ms failure, although I'm not actually sure if it's related because ListenBrainz should still have been accepting scrobbles. The other time is more recently today, where, despite there not being an incident a scrobble failed and a queue built up.

The first time, a reboot did fix the issue, however naturally cleared the scrobbles from the queue which I think is less than ideal, one solution could be to possible save queued scrobbles into a temporary file? I haven't restarted it today just in case it turns out there's something I've missed that can help resume scrobbling!

**Comment by TheFeelTrain** [comment]
This is happening to me constantly. ListenBrainz seems to lose connection pretty often and requires a restart every time which means losing all of the scrobble backlog.

**Comment by Cwavs** [comment]
This is good to know. At the time of the logs that I posted, as far as I am aware, LB wasn't having any downtime or issues with scrobbles and I left MS up (without it reactivating) for quite a while until I was forced to restart it to install some updates. Does this sound like an issue with my set up or my home network? LastFM continued to work properly throughout this period. 

Unfortunately as it was quite a while back now I don't believe I have any logs saved still from that time, so I'll make sure to keep an eye out for the issue and send any logs your way.

I also think it may still be worth considering store queued scrobbles somewhere so they can persist through restarts, to protect against a longer period of downtime where a server restart might be needed.

As always, thanks for your hard work maintaining this project!

**Comment by TheFeelTrain** [comment]
I have the logs of it working fine and then suddenly failing. You can ignore the errors about the WebScrobbler, that was [this](https://github.com/FoxxMD/multi-scrobbler/issues/111#issuecomment-1837183780) which has already been resolved. 

[scrobble-2023-12-02.log](https://github.com/FoxxMD/multi-scrobbler/files/13783277/scrobble-2023-12-02.log)

This log in particular shows it suddenly fails to scrobble and continues retrying over and over until I restarted the whole container. After the restart (bottom of the log) it works again even though nothing about the ListenBrainz config has changed. You can also see Last.fm and Maloja successfully scrobbling in the middle while ListenBrainz is still failing on the previous one. 

Without restarting the container the request will just keep failing over and over with the client set to "Idle" and all of the scrobbles end up queued which you can see in this log from today: [scrobble-2023-12-27.log](https://github.com/FoxxMD/multi-scrobbler/files/13783334/scrobble-2023-12-27.log)

In fact my last 3+ days of logs is just this repeating since I don't listen to music that often.

I am curious to see if the manual restart will work since it seems like it is trying to restart with the heartbeat occurs. Let me know if you need any more info and I will let you know how it goes when this inevitably happens again.

**Comment by FoxxMD** [comment]
@TheFeelTrain thanks for the logs that helped me isolate the issue:

* MS was treating 400 (bad request) responses as service errors from LZ (stop the client) when it should have been treating them as individual scrobble errors (move scrobble to failure queue)
* It seems Jellyfin can return multiple LZ artist mbids in a single string which can be seen in your logs as `..."artist_mbids":["fad8967c-a327-4af5-a64a-d4de66ece652;100846a7-06f6-4129-97ce-4409b9a9a311"]...` which what was causing the LZ 400 response

I've fixed both of these issues in `foxxmd/multi-scrobbler:develop` docker image. Please try it out and let me know if it resolves your issue.

**Comment by TheFeelTrain** [comment]
Now it seems that the Last.fm API doesn't like your changes 😅
[scrobble-current.log](https://github.com/FoxxMD/multi-scrobbler/files/13791962/scrobble-current.log)

**Comment by FoxxMD** [comment]
Oops! Overlooked something when making these changes. Thanks for the logs, I'll have this fixed soon.

**Comment by FoxxMD** [comment]
@TheFeelTrain this should be fixed in `develop` image. Let me know if you have any more issues.

**Comment by FoxxMD** [comment]
[Fixed in 0.6.3](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.6.3)
