### ISSUE TITLE
Request: Add ability to import Apple Music data

### ISSUE THREAD

**Issue by nolageek** [FoxxMD/multi-scrobbler#154]
Could you add the ability to import Apple Music data from the data export files?

**Comment by FoxxMD** [comment]
What data export file are you referring to?

**Comment by FoxxMD** [comment]
If you would like to reopen this with more details let me know. Generally, multi-scrobbler is designed for real-time scrobble rather than importing existing data. You may want to look at importing data in [maloja](https://github.com/krateng/maloja?tab=readme-ov-file#data) or open an issue there for getting whatever data you are talking about into a self-hosted scrobble server.
