### ISSUE TITLE
0.8.0 Configuration Normalization info

### ISSUE THREAD

**Issue by b9AcE** [FoxxMD/multi-scrobbler#165]
Regarding the "breaking change" of the "Configuration Normalization" in [version 0.8.0](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.8.0)  I'm just wondering,
as it is written in those releasenotes ("`This is a breaking change but MS will continue to operate without any changes to your config.`") it could be understood as there currently being some kind of compatibility mode phase where both the old and new formats are working concurrently.
Is that the case?

If so, is there somewhere we would get some info/warning regarding configuration that must be migrated before that compatibility phase ends?
I could not see any such in my MS logs output and scrobbling remains fully functional as it was before re-pulling docker compose using "image: foxxmd/multi-scrobbler".
Does that mean no migration is needed?

**Comment by FoxxMD** [comment]
There is no deprecation phase for the config changes and there is no way to get warnings about these changes. 

**However, MS will not fail to operate because the changes have not been made, it simply will not see the old config properties anymore (until they have been moved).**

I do plan to add actual config validation checks (and deprecation warnings) back in in the future but they currently do not run. The config schema is solely for [viewing documentation](https://json-schema.app/view/%23?url=https%3A%2F%2Fraw.githubusercontent.com%2FFoxxMD%2Fmulti-scrobbler%2Fmaster%2Fsrc%2Fbackend%2Fcommon%2Fschema%2Faio.json) though you can also use this site to check your config validity by copy-pasting your config into the right-hand pane.

Sorry for the confusion with my wording in the release. Below is a list of the properties that have been moved and how to migrate them. I'll mention this in the release.

# To Migrate Configs

All configs already had a  `data` property but now also have an (optional) `options` property at top-level.

```json5
[
  {
    "name": "Deezer",
    "data": {
		// ...
    },
    "options": {
       // ...
	}
  }
]
```

If this property does not exist you must create it before moving any of the listed properties. **If you do not have any of the listed properties in your configs you do not need to do anything (including creating `options`).**

## For both Source and Clients

* [`scrobbleThresholds`](https://json-schema.app/view/%23/%23%2Fdefinitions%2FChromecastSourceAIOConfig/%23%2Fdefinitions%2FCommonSourceOptions/%23%2Fdefinitions%2FScrobbleThresholds?url=https%3A%2F%2Fraw.githubusercontent.com%2FFoxxMD%2Fmulti-scrobbler%2Fmaster%2Fsrc%2Fbackend%2Fcommon%2Fschema%2Faio.json)
* `maxPollRetries`
* `maxRequestRetries`
* `retryMultiplier`

Should be moved from `data` to `options`.

## For Clients only

There was a `data.options` property like:

```json5
{
// ...
  "data": {
   // ...
   "options": { ... }
   }
}
```

This should be moved to be a sibling of `data` like:

```json5
{
// ...
  "data": {
   // ...
   },
   "options": { ... }
}
```

___

Additionally you can reference:

* [config example](https://github.com/FoxxMD/multi-scrobbler/blob/master/config/config.json.example)
* [kitchen sink example](https://foxxmd.github.io/multi-scrobbler/docs/configuration/kitchensink)
* [`options` schema for Sources](https://json-schema.app/view/%23/%23%2Fdefinitions%2FSpotifySourceAIOConfig/%23%2Fdefinitions%2FCommonSourceOptions?url=https%3A%2F%2Fraw.githubusercontent.com%2FFoxxMD%2Fmulti-scrobbler%2Fmaster%2Fsrc%2Fbackend%2Fcommon%2Fschema%2Faio.json)
* [`options` schema for Clients](https://json-schema.app/view/%23/%23%2Fdefinitions%2FMalojaClientAIOConfig/%23%2Fdefinitions%2FCommonClientOptions?url=https%3A%2F%2Fraw.githubusercontent.com%2FFoxxMD%2Fmulti-scrobbler%2Fmaster%2Fsrc%2Fbackend%2Fcommon%2Fschema%2Faio.json)

to verify your config is correct.

**Comment by b9AcE** [comment]
Thank you for the ample clarification.

As there "is no deprecation phase for the config changes",
would it then be correct to assume that if everything appears to remain working as as desired after the upgrade,
that means these changes require no further action in such cases?

**Comment by FoxxMD** [comment]
Yes that is a fair assumption. 

Part of the motivation for moving these settings to `options` was to differentiate between "required" or major-behavioral settings in `data` IE credentials, filters for not scrobble certain users in jellyfin, blacklisting apps in chromecast...

vs. "optional" settings or settings used for fine-tuning MS experience that don't primarily effect scrobbling/monitoring IE polling interval, number of request retries, more verbose logging...

All of the settings that were migrated to `options` in this change are the latter. 

In 95% of cases users won't have these settings listed anyways. In the remaining 5% the change may result in some un-optimal behavior IE source stopping early due to network issues that were compensated for by higher # of allowed retries. In 0% of cases should these changes break MS, though.

**Comment by b9AcE** [comment]
Very good.
I hope my questions and your answers will also benefit other users who might have had similar questions in mind.
With that, I have no further questions on this and am closing the issue.
