### ISSUE TITLE
BUG: No scrobbling when using Spotify connect

### ISSUE THREAD

**Issue by DieSteinhose** [FoxxMD/multi-scrobbler#51]
Due to a seeming bug at Spotify, it is (currently?) not possible to get songs via the `recently-played` api endpoint, which were played via Spotify connect. The endpoint `currently-playing` shows the correct song though.

Is there a way to include this as a fallback?

Greetings

**Comment by FoxxMD** [comment]
Do you have evidence recently-played explicitly excludes tracks played via spotify connect? Or have you seen this occur over a prolonged period?

`recently-played` only updates _after_ spotify sees you "move on" from the current track. The track needs to have been played at least 30 seconds, then the player need to have been stopped for some amount of time (minutes?) OR a new track needs to be "currently played".

Additionally, sometimes spotify doesn't updated recently-played for a _long_ time. I've seen it stay stale for several hours at a time. 

To verify:

* Play a track for at least 50% of its play duration using spotify connect
* Switch to the normal spotify player and play a different track for at least 50% of its play duration
* Wait for `recently-played` to update -- you can check this by getting the raw list result from the MS ui 

![image](https://user-images.githubusercontent.com/4663766/192572254-5688d907-631f-4d57-a347-89d054c3eb76.png)

_after_ recently played is updated with the song from the normal player let me know if the spotify connect track does not show in recently played.

**Comment by DieSteinhose** [comment]
I first noticed this behavior a few weeks ago, and since then the Spotify connect songs were always left out. 

I just went through the steps, and yes exactly. The Spotify player song are displayed there and the Spotify connect are not.

**Comment by FoxxMD** [comment]
Ok, thanks for verifying.

I looked into it but don't have any good news for you...

* The [recently-played](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recently-played) documentation mentions nothing about spotify connect, specifically
* The [spotify connect](https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/) documentation also does not mention anything about recently played not working or excluded
* There are [quite](https://community.spotify.com/t5/Spotify-for-Developers/Recently-played-API-endpoint-does-not-show-latest-played-tracks/m-p/5289081/highlight/true#M3547) a [few](https://community.spotify.com/t5/Ongoing-Issues/Mobile-Recently-Played-not-updating/idc-p/5433091/highlight/true#M129978) instances of recently played being inconsistent in what it tracks with more than a few mentions of spotify connect

There is not much recourse for fixing this on my end, I think.

**Comment by DieSteinhose** [comment]
hej, in the meantime I found out that it is not a bug of Spotify Connect, but of the implementation that uses the application that I use. I use [HiFiBerryOS](https://github.com/hifiberry/hifiberry-os) and this uses [librespot](https://github.com/librespot-org/librespot) at the end.

Here is the [issue](https://github.com/librespot-org/librespot/issues/913) about it and as it seems, this will not be fixed in a timely manner either.

You said that you can implement this using the existing MemorySource. Is this a lot of work?

**Comment by FoxxMD** [comment]
> Here is the issue about it

Thanks that was enlightening. So it seems that spotify requires the client to report that a track has been played rather than the server (spotify) keeping track of it. And that track reporting is part of their private API. So really any client using spotify connect (since its 3rd party by nature) will not have tracks played by that client reported to recently-played.

> You said that you can implement this using the existing MemorySource. Is this a lot of work?

It will require refactoring either the existing Spotify implementation or MemorySource code to work as a hybrid. They are somewhat mutually exclusive right now as their "source of truth" for recently played tracks comes from totally different places.

**Comment by FoxxMD** [comment]
@DieSteinhose 

I got [Spot](https://github.com/xou816/spot) running but spotify does not return any information for currently-playing or even used devices when using it. 

Re-reading the [librespot discussion](https://github.com/librespot-org/librespot/discussions/626#discussioncomment-576296) it seems like "currently-playing" and "recently-played" should be intrinsically linked: if a player is reporting what is being played than it would automatically be recorded to "recently-played" by spotify (so they are not two independent actions by the client).

Since librespot is reversed engineered it has no contract to report played tracks -- the music you listened to is only downloaded by the client and spotify distinguishes between downloaded vs. played.

> The endpoint currently-playing shows the correct song though.

What endpoint are you talking about? Are you saying that using your forked version of spotifyd from hifiberryos you get a correct response from the [currently-playing](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-the-users-currently-playing-track) endpoint?

**Comment by FoxxMD** [comment]
@DieSteinhose 

I've got some changes in that should work for your scenario! Please try MS using either the git branch `spotifyConnect` or with the docker image `foxxmd/multi-scrobbler:experimental`

You should re-authenticate your spotify source after the first run to get new credentials with more permissions.

**Comment by FoxxMD** [comment]
Added in [v0.4.2](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.4.2) and available in

* `master` git branch
* `foxxmd/multi-scrobbler:latest` docker image tag
* `foxxmd/multi-scrobbler:0.4.2` docker image tag

**Comment by DieSteinhose** [comment]
Sry for the late answer. I was on the trip, but in the meantime I updated the container. Since then there were two error messages and the scrolling stopped.

```
2023-03-11T08:29:45+01:00 info   : [Client Maloja - ***Maloja] Scrobbled (New)     => (Spotify) Linkin Park - Lost @ 2023-03-11T08:27:53+01:00
2023-03-11T09:40:53+01:00 warn   : [Source - Spotify - Spotify ] Request failed but retries (0) less than max (1), retrying request after 2 seconds...
2023-03-11T09:40:55+01:00 error  : [Source - Spotify - Spotify ] Request failed on retry (1) with no more retries permitted (max 1)
2023-03-11T09:40:55+01:00 error  : [Spotify                    ] WebapiError: [object Object] [{"label":"Spotify"}]
    at _toError (/app/node_modules/spotify-web-api-node/src/http-manager.js:47:10)
    at /app/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/app/node_modules/superagent/lib/node/index.js:867:3)
    at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/index.js:1070:18)
    at Stream.emit (node:events:513:28)
    at Unzip.<anonymous> (/app/node_modules/superagent/lib/node/unzip.js:54:12)
    at Unzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-03-11T09:40:55+01:00 error  : [Source - Spotify - Spotify ] Error occurred while trying to retrieve current playback state: [object Object]
2023-03-11T09:40:55+01:00 error  : [Source - Spotify - Spotify ] Error occurred while polling
2023-03-11T09:40:55+01:00 error  : [Source - Spotify - Spotify ] WebapiError: [object Object]
    at _toError (/app/node_modules/spotify-web-api-node/src/http-manager.js:47:10)
    at /app/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/app/node_modules/superagent/lib/node/index.js:867:3)
    at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/index.js:1070:18)
    at Stream.emit (node:events:513:28)
    at Unzip.<anonymous> (/app/node_modules/superagent/lib/node/unzip.js:54:12)
    at Unzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-03-11T09:40:55+01:00 warn   : [Source - Spotify - Spotify ] Poll retries (0) equal to max poll retries (0), stopping polling!
```

In the meantime, I have tinkered my [own solution](https://github.com/DieSteinhose/HiFiBerry-to-maloja-for-Spotify). But it works only between HifiBerry and Maloja and this is my first Python project, as a noob, this was surprising not so difficult.

But thanks for implementing the feature here.

**Comment by FoxxMD** [comment]
I have not been able to reproduce your error. It looks like a regular service issue upstream from spotify rather than an issue with MS. Also, the first line looks like spotify was working due to scrobbling the linkin park track?

> Since then there were two error messages 

Does this mean it _was_ working fine (was tracking music and scrobbling to maloja) but then stopped at some point? That would mean it was just spotify's api being unavailable.
