### ISSUE TITLE
Feature: Trakt support

### ISSUE THREAD

**Issue by blackwind** [FoxxMD/multi-scrobbler#54]
Any thoughts on expanding into video scrobbling via Trakt?

**Comment by FoxxMD** [comment]
I'm not sure I understand the use-case here. It looks like Trakt already records your watches. Do you want to record movies to Maloja? Or pull from Trakt to another source?

**Comment by blackwind** [comment]
So, with Plex, there's no ability to scrobble video without paying for Plex Pass AND Trakt. If I could do it from the same service that handles my Last.fm scrobbling, that'd be tremendously useful to me (and, I think, other Plex users).

**Comment by FoxxMD** [comment]
MS is not suitable for this for a few reasons:

* it only tracks a few fields of which only a few are relevant to movies/tv
* the scrobble metric isn't very useful here since you would need to watch at least (?) 50% of an item before Plex even decides to register it. If you watch 13 minutes of a 30 minute show MS wouldn't record it.
* Maloja also does not have fields suitable for classifying movies/tv...

If your goal is to track your watch history and have an interface for seeing history + some stats/graphs you are going to be better off using [**Tautulli**](https://tautulli.com) which integrates with Plex without the need for Plex Pass and is purpose-built for exactly those requirements (it can also track music!)
