### ISSUE TITLE
Spotify stops polling and then does not restart anymore automatically and without notification.

### ISSUE THREAD

**Issue by iluvatyr** [FoxxMD/multi-scrobbler#65]
I was checking my scrobbles and suddenly noticed that many scrobbles of the last days are missing. So I manually checked the logs of the multiscrobber and noticed that it stopped scrobbling tracks from spotify since half a month already. The tracks I played there are therefore lost now.  

I think it would be best, if there was a container internal mechanism implemented that tries polling again after a defined time, because there is no way someone wants to constantly check if the scrobbling is still working. 

Secondly, it would be great to have an additional email or other notification that can be configured to inform the user that there is an issue regarding something in multi-scrobbler.

Options to inform user about an issue with multi-scrobbler:
- Health page multi-scrobbler-domain/health that can be monitored using uptime-kuma / uptimerobot
- Docker internal health check
- Email / Webhook notification

Logs are here:

```
2023-01-14T02:21:20+01:00 warn : [Source - Spotify - unnamed] Poll retries (0) equal to max poll retries (0), stopping polling!
2023-01-14T02:21:20+01:00 error : [Source - Spotify - unnamed] Error: getaddrinfo ENOTFOUND api.spotify.com
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) ,2023-01-14T02:21:20+01:00 error : [Source - Spotify - unnamed] Error occurred while polling
2023-01-14T02:21:20+01:00 error : [Spotify ] Error: getaddrinfo ENOTFOUND api.spotify.com [{"label":"Spotify"}]
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) ,2023-01-14T02:21:20+01:00 error : [Source - Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
2023-01-14T02:21:18+01:00 warn : [Source - Spotify - unnamed] Request failed but retries (0) less than max (1), retrying request after 2 seconds...```

**Comment by iluvatyr** [comment]
Hello, I see you closed this, but it is not entirely clear to me how to fix this now. 
First and foremost, I do not know, which values would be appropriate for the above to not happen anymore.
Secondly, how is setting this possible in an ENV-Configuration, not using config files? is it even possible?

If you do not have a lot of time for a health check, I think a get request to a custom URL on a poll stopping or error coming up would already be enough for a lot of things

**Comment by FoxxMD** [comment]
>  which values would be appropriate for the above to not happen anymore.

I've recently rewritten the [documentation](https://github.com/FoxxMD/multi-scrobbler/blob/master/docs/configuration.md) and it now includes a schema explorer for each config file and the general `config.json` file. [Here is the explorer for the general config](https://github.com/FoxxMD/multi-scrobbler/blob/master/docs/configuration.md) (also linked in the docs). The explorer contains descriptions, examples, and a live editor/validator. The `sourceDefaults` property is the one you are interested in.

To increase the polling attempts you could have a `config.json` file that contains only this:

```json
{
  "sourceDefaults": {
    "maxRequestRestries": 3,
    "maxPollRetries": 12,
    "retryMultiplier": 10
  }
}
```

Which will make MS:
* Attempt any request 3 times before failing
* Try to restart polling 12 times before giving up
* Wait `# of attempts * 10 seconds` seconds between each polling retry attempt

> is setting this possible in an ENV-Configuration

No it is not. The ENV based config is for supporting the _bare minimum_ setup for MS. 

On the code side I already have to structure all this user data into something equivalent to json (nested objects) so it's much easier to use config files for that input since I can easily validate and parse that complex/nested data. MS already has ~20 ENV variables I have to support alongside the regular config files and I don't plan on adding many more if possible.

**Comment by iluvatyr** [comment]
Hello FoxxMD, 

Thank you! I was just finished with my process of converting all the environment variables to jsons when you posted this. The documentation is showing nicely how to format the json files. It worked on first try.
I just didnt know exactly what values are appropriate since I do not know the polling mechanism and how it should be for not trying too long but still long enough.

Thank you for showing me some values that I will use.
