### ISSUE TITLE
Instructions Unclear, Built A Table.

### ISSUE THREAD

**Issue by stayupthetree** [FoxxMD/multi-scrobbler#8]
Wanted to test it out, but had to come all the way to the Git hub to learn how to configure it. You have sample configs on the github, would it be possible to include those when installing in Unraid? Because right now all the appdata folders are empty, including the samples you already had created would be helpful.

**Comment by FoxxMD** [comment]
Thanks for the feedback!

In the short term I will add more info about configuration in the unraid post. 

I'm not already including the examples when using docker because it's new to me and I'm certain i'll have to do some permission checking and UID stuff in the dockerfile and in the app. Once I've experimented with that and am sure I'm not going to overwrite or break things I'll add them!

**Comment by FoxxMD** [comment]
Example configs are now copied to fresh config folders when using docker in [v0.4.0](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.4.0)
