### ISSUE TITLE
Duplicates of artists scrobbled to Maloja with ListenBrainz as source

### ISSUE THREAD

**Issue by ghost** [FoxxMD/multi-scrobbler#90]
I'm using ListenBrainz as a source to scrobble to my [Maloja](https://github.com/krateng/maloja) client. It works fantastic with multiple artists most of the time.

Except for when I'm scrobbling to ListenBrainz through [Pano Scrobbler](https://github.com/kawaiiDango/pScrobbler).

Here's an example:

`2023-07-25T17:06:18-04:00 debug : [Scrobblers] [Maloja - Maloja] Raw Payload: {"album":"3.15.20","artists":["Childish Gambino, Ariana Grande","Childish Gambino","Ariana Grande"],"key":KEY","time":1690319040,"title":"Time"}
2023-07-25T17:06:18-04:00 info : [Scrobblers] [Maloja - Maloja] Scrobbled (Backlog) => (listenbrainz) Childish Gambino, Ariana Grande / Childish Gambino / Ariana Grande - Time @ 2023-07-25T17:04:00-04:00`

And it ends up looking like this:
`Childish Gambino, Ariana Grande, Childish Gambino, Ariana Grande - Time`

where the first two artists are grouped together as a single artist, and the last two are their own separate ones.

Thank you for your time.

**Comment by FoxxMD** [comment]
Please try `foxxmd/multi-scrobbler:develop` docker image or `develop` branch and let me know if this resolves your issue.

**Comment by FoxxMD** [comment]
What the is original source of the listens? As in, before they are recorded to listenbrainz (as sent by pano scrobbler)?

Or if you can give me your listenbrainz user name so I can get your history to test with I might be able to get some more hints.

___

Listenbrainz is a hard source to work with. The problem is they provide _too much_ information and also don't indicate which pieces of information are correct. For example, here is the listen payload from listenbrainz for Annhilate, as listened to from Spotify:

![annihilate_annot](https://github.com/FoxxMD/multi-scrobbler/assets/4663766/5da6d569-68c2-4d4b-8116-f1859f299423)

The fields `artist_name` and `track_name` are what **your client sent** to Listenbrainz as the "raw data" for that listen. 

Everything under `mbid_mapping` (`artist_credit_name` and `recording_name`) are what listenbrainz **thinks** this listen's official musicbrainz release is.

The issue is that listenbrainz has some level confidence as to whether what it matched is "correct" but this is not returned in the listen payload. You can see the confidence by looking at your LB history -- high confidence listens are bolded while low confidence are muted. 

![image](https://github.com/FoxxMD/multi-scrobbler/assets/4663766/44b3ceaf-f816-4be6-875b-6ae6364222b1)

Additionally, LZ is happy to return a listen with an incorrect match and does not indicate this in the response.

So it's not really possible to rely solely on LZ's match data for sending scrobbles. However, when its correct, the match data can be very useful for filling out scrobble details.

MS does a bit of simple matching to try to determine if what you recorded (`artist_name` `track_name`)  matches what LZ provides in the match data. If it does not match then it _should_ fall back to only using `artist_name` `track_name` for artist - track -- and at point it's really at the mercy of whatever client initially sent to the scrobble to LZ to correctly format that data. 

EX being the first screenshot -- the spiderverse album on spotify has every dang artists _also in the track name_ which means i can't match the track name proper and it'll end up sending it with "duplicated" artists to maloja.

___

All of that is to say, I can't really reproduce your issue without also having the raw data sent from LZ so your profile username or more info on the source of the scrobbles may help.

**Comment by FoxxMD** [comment]
You can try updating to the newest `develop` image and see if this helps at all. It should at least cover common patterns like your first example where artist or track is like `PRIMARY (ft. SECONDARY, etc.)`

**Comment by FoxxMD** [comment]
Ok I'm looking into all of this again. Thanks for all the detailed logs and your username. Just to confirm -- you have updated to the latest `develop` docker image (or git branch)?

**Comment by FoxxMD** [comment]
I've rewritten the listenbrainz parser and it should do a *much* better job of parsing all of these use-cases now. 

I wrote a [test suite](https://github.com/FoxxMD/multi-scrobbler/blob/develop/src/server/tests/listenbrainz.test.ts) using all of these examples + others from your history (and mine) which the parser now passes with flying colors. 

![image](https://github.com/FoxxMD/multi-scrobbler/assets/4663766/8358c217-6250-4c45-90e8-d81cec0b93a7)

Please update to the latest `develop` docker image/git branch and try it out. If you find anymore examples please let me know.
